### ISSUE TITLE
Cannot build Docker image

### ISSUE THREAD

**Issue by jinnatar** [AntilaX-3/docker-efergyexporter#1]
Current Docker image fails to build:
```
> efergyexporter@1.0.0 build
> backpack build

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at filename (/app/node_modules/babel-loader/lib/fs-cache.js:76:21)
    at /app/node_modules/babel-loader/lib/fs-cache.js:107:37
    at /app/node_modules/mkdirp/index.js:30:20
    at FSReqCallback.oncomplete (node:fs:188:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.3.0
```

If I bump the image from `node:alpine3.12` to `node:alpine` it still fails, just with a newer Node:

```
> efergyexporter@1.0.0 build
> backpack build

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at filename (/app/node_modules/babel-loader/lib/fs-cache.js:76:21)
    at /app/node_modules/babel-loader/lib/fs-cache.js:107:37
    at /app/node_modules/mkdirp/index.js:30:20
    at FSReqCallback.oncomplete (node:fs:188:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.4.0
```

If instead I fix the builder image at `alpine:3.12` instead of `alpine:latest`:
```
> efergyexporter@1.0.0 build
> backpack build

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at filename (/app/node_modules/babel-loader/lib/fs-cache.js:76:21)
    at /app/node_modules/babel-loader/lib/fs-cache.js:107:37
    at /app/node_modules/mkdirp/index.js:30:20
    at FSReqCallback.oncomplete (node:fs:188:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.3.0
```

So it seems that no matter the images, the Node app just fails to build.

**Comment by jinnatar** [comment]
Since this made the project unusable, I created my own exporter that does the same thing: https://github.com/artanicus/efergy_exporter/

**Comment by nightah** [comment]
The issue specifically has to do with a change in Node, it's a one-liner to fix it.

Sorry for the delay in the response I just saw the notification from your last message.

**Comment by nightah** [comment]
Fixed by https://github.com/antilax-3/docker-efergyexporter/commit/8f6378dd5a6e302c404e445f8c8cfeb9b85de750.
